name: Deploy ACME Shared Client to CodeArtifact (DEV only)

# Elle veya push ile çalıştırmak istersen:
on:
  workflow_dispatch:    # elle tetikleyebilir, ayrıca
  push:
    branches: [ main ]  # main'e push olduğunda otomatik tetiklenir

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
      REPO_NAME: acme-maven-dev
      DOMAIN_NAME: acme-domain
      FORMAT: maven
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (DEV)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}



      - name: Get CodeArtifact auth token (DEV)
        id: token
        run: |
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${DOMAIN_NAME} \
            --domain-owner ${{ secrets.DEV_AWS_ACCOUNT_ID }} \
            --region ${AWS_REGION} \
            --query authorizationToken --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Deploy with Maven (DEV)
        run: mvn -B -Pdev -s settings.xml deploy -DskipTests
